name: Scan
on:
  push:
    branches:
      - grype
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout playground
        uses: actions/checkout@v4.2.0
        with:
          repository: 'SabrinaPloner/renovate-vulnerability-playground'
          token: ${{ secrets.RENOVATE_PLAYGROUND_TOKEN}}

      - name: Check 1
        run: docker version

      - name: Scan repository
        run: docker run --rm --volume .:/scan anchore/grype:latest /scan -o table > grype-output.txt

#      - name: Build the Container image
#        run: docker build . --file docker/Dockerfile --tag localbuild/testimage:latest

#      - name: Scan docker image
#        uses: anchore/scan-action@v3
#        id: scan
#        with:
#          image: "localbuild/testimage:latest"
#          fail-build: false
#          only-fixed: 'true'
#          output-format: 'table'

      - name: Check 2
        run: ls -l

      - name: Check 3
        run: cat grype-output.txt

#      - name: Transform table
#        run:  bash scripts/transform-table.sh
#
#      - name: Check
#        run: bash ls results