name: Trigger Renovate
on:
  push:
    branches:
      - main
  #schedule:
  # The "*" (#42, asterisk) character has special semantics in YAML, so this
  # string has to be quoted.
  # - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.3.1
        with:
          configurationFile: renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}