name: Trigger Renovate
on:
  push:
    branches:
      - grype
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Checkout playground
        uses: actions/checkout@v4.2.0
        with:
          repository: 'SabrinaPloner/renovate-vulnerability-playground'
          token: ${{ secrets.RENOVATE_TOKEN }}
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.3.1
        with:
          configurationFile: renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}