name: Renovate
on:
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.3.1
        with:
          configurationFile: renovate-config.json
          token: ${{ secrets.RENOVATE_PLAYGROUND_TOKEN}}
        env:
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
