name: Trigger Renovate
on:
  workflow_run:
    workflows: [ "Scan" ]
    types: [ completed ]
    branches:
      - 'grype'

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

  renovate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.3.1
        with:
          configurationFile: renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}